backend:
  name: github
  repo: wjq-glarysoft/astro-decap-starter-ssr
  branch: master
  site_domain: astro-ssr-blog.1003056522.workers.dev
  base_url: https://astro-ssr-blog.1003056522.workers.dev
  auth_endpoint: oauth

media_folder: src/assets/img
public_folder: src/assets/img

collections:
  - name: "post"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Slug", name: "slug", widget: "string", required: true }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Categories", name: "categories", widget: "list", field: { label: "Category", name: "category", widget: "string" } }
      - { label: "Body", name: "body", widget: "markdown" }