# public/admin/config.yml
backend:
  name: github
  repo: wjq-glarysoft/astro-ssr-blog  # 请替换为实际值
  branch: master

media_folder: "public/img"
public_folder: "/img"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }